---
# Required in some selinux policy versions see
# https://bugzilla.redhat.com/show_bug.cgi?id=1587825
# https://bugzilla.redhat.com/show_bug.cgi?id=1549765
- name: Setting sebool container_manage_cgroup
  seboolean:
    name: container_manage_cgroup
    state: yes
    persistent: yes
  # add the following lines to skip the task if we do not need it
  when:
    - ansible_selinux
    - ansible_selinux.status == 'enabled'

